"""The leak guard: CI fails if anything resembling patient data enters the tree.

The dataset behind this project is licensed videofluoroscopy of real patients.  The
code and the metrics are publishable; the frames are not.  A reviewer should not have
to take that on trust, so the invariant is a test.

This runs on every push and every pull request.
"""

from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]

#: Raster formats that could carry an image of a patient.
RASTER_SUFFIXES = {
    ".jpg",
    ".jpeg",
    ".bmp",
    ".tif",
    ".tiff",
    ".webp",
    ".dcm",
    ".dicom",
    ".nii",
    ".npy",
    ".npz",
}

#: Video containers used by the source studies.
VIDEO_SUFFIXES = {".avi", ".mp4", ".mov", ".mkv", ".wmv"}

#: Directories generated by tooling that are not part of the committed tree.
IGNORED_DIRECTORIES = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
}

MAX_FILE_BYTES = 5 * 1024 * 1024


def iter_tracked_files() -> list[Path]:
    """Every file in the working tree, excluding tooling directories."""
    files = []
    for path in REPO_ROOT.rglob("*"):
        if not path.is_file():
            continue
        if IGNORED_DIRECTORIES.intersection(path.relative_to(REPO_ROOT).parts):
            continue
        files.append(path)
    return files


class TestNoImagery:
    def test_no_raster_image_formats_are_committed(self) -> None:
        """PNG is allowed (charts only, checked below); every other raster format is not."""
        offenders = [
            p.relative_to(REPO_ROOT) for p in iter_tracked_files() if p.suffix.lower() in RASTER_SUFFIXES
        ]
        assert offenders == [], f"raster files that could contain a radiograph: {offenders}"

    def test_no_video_files_are_committed(self) -> None:
        offenders = [
            p.relative_to(REPO_ROOT) for p in iter_tracked_files() if p.suffix.lower() in VIDEO_SUFFIXES
        ]
        assert offenders == [], f"video files committed: {offenders}"

    def test_committed_pngs_are_charts_not_photographs(self) -> None:
        """Charts are mostly flat white; a radiograph is mostly mid-tone grey.

        The threshold is deliberately loose. Its job is to catch a frame that was
        pasted into the tree by accident, not to classify images finely.
        """
        pillow = pytest.importorskip("PIL.Image")
        numpy = pytest.importorskip("numpy")

        suspects = []
        for path in iter_tracked_files():
            if path.suffix.lower() != ".png":
                continue
            with pillow.open(path) as handle:
                pixels = numpy.asarray(handle.convert("RGB").resize((128, 128)))
            channel_max = pixels.max(axis=2).astype(int)
            channel_min = pixels.min(axis=2).astype(int)
            grey = channel_max - channel_min < 12
            mid_tone_grey = float((grey & (channel_max > 25) & (channel_max < 235)).mean())
            if mid_tone_grey > 0.25:
                suspects.append((path.relative_to(REPO_ROOT), round(mid_tone_grey, 3)))
        assert suspects == [], f"PNGs whose tone distribution looks photographic: {suspects}"


class TestNoNotebooks:
    def test_no_notebooks_are_committed(self) -> None:
        """Notebook outputs are an unreviewable base64 channel for images.

        The original repository carried 3.4 MB of them. This project ships scripts
        instead; see docs/adr/0001-scripts-not-notebooks.md.
        """
        offenders = [p.relative_to(REPO_ROOT) for p in iter_tracked_files() if p.suffix == ".ipynb"]
        assert offenders == [], f"notebooks committed: {offenders}"


class TestRunArchive:
    ARCHIVE = REPO_ROOT / "results" / "runs.jsonl"

    #: Anything that could identify a machine, a study, a frame or a patient.
    FORBIDDEN = (
        (re.compile(r"[A-Za-z]:\\\\"), "Windows absolute path"),
        (re.compile(r"/(?:home|Users|mnt|media)/"), "POSIX absolute path"),
        (re.compile(r"\.(?:jpe?g|png|avi|mp4|dcm|tiff?)\b", re.IGNORECASE), "media filename"),
        (re.compile(r"\bvideo\d+\b", re.IGNORECASE), "source video identifier"),
        (re.compile(r"\bframe\d+\b", re.IGNORECASE), "extracted frame identifier"),
        (re.compile(r"\b\d{2}[-/]\d{2}[-/]\d{4}\b"), "acquisition date"),
        (re.compile(r"\bpatient\b", re.IGNORECASE), "patient reference"),
    )

    def test_archive_exists(self) -> None:
        assert self.ARCHIVE.is_file()

    def test_archive_contains_no_identifying_strings(self) -> None:
        text = self.ARCHIVE.read_text(encoding="utf-8")
        found = [label for pattern, label in self.FORBIDDEN if pattern.search(text)]
        assert found == [], f"run archive contains {found}"

    def test_archive_exposes_only_the_allowlisted_shape(self) -> None:
        """A new key in the export is a review event, not a silent addition."""
        allowed_top = {"model_hash", "config", "history", "pixel_error", "n_train", "n_valid", "is_complete"}
        allowed_config = {
            "model_name",
            "loss_type",
            "num_keypoints",
            "architecture",
            "num_epochs",
            "batch_size",
            "learning_rate",
            "k_folds",
            "scheduler_type",
            "freeze_backbone",
            "augmentation_params",
            "dataset_expansion",
            "few_shot",
            "seed",
        }
        allowed_history = {"train_losses", "valid_losses", "train_pixel_errors", "valid_pixel_errors"}

        with self.ARCHIVE.open(encoding="utf-8") as handle:
            for lineno, line in enumerate(handle, start=1):
                if not line.strip():
                    continue
                record = json.loads(line)
                assert set(record) <= allowed_top, (
                    f"line {lineno}: unexpected keys {set(record) - allowed_top}"
                )
                assert set(record.get("config", {})) <= allowed_config, (
                    f"line {lineno}: unexpected config keys"
                )
                assert set(record.get("history", {})) <= allowed_history, (
                    f"line {lineno}: unexpected history keys"
                )

    def test_archive_holds_no_per_image_values(self) -> None:
        """Per-image error vectors are patient-linked and must never be exported.

        Every array in the archive is per-epoch, so its length is bounded by the
        epoch budget (100). A 297-long array would be one value per validation frame.
        """
        with self.ARCHIVE.open(encoding="utf-8") as handle:
            for lineno, line in enumerate(handle, start=1):
                if not line.strip():
                    continue
                record = json.loads(line)
                budget = record.get("config", {}).get("num_epochs", 100) or 100
                for name, series in (record.get("history") or {}).items():
                    assert len(series) <= budget, (
                        f"line {lineno}: {name} has {len(series)} entries, budget is {budget}"
                    )


class TestExporterRefusesUnhashedRuns:
    """The exporter must never substitute a private directory name for a missing hash.

    ``tools/export_runs.py`` is the only bridge out of the private research repo, and
    its own docstring promises that "directory names of the private machine" are not
    exported.  A ``summary.get("model_hash") or model_dir.name`` fallback broke that
    promise: a run whose summary lost its hash would have published the folder it was
    trained in — plausibly a study or machine name.

    ``TestRunArchive`` cannot catch this. Its allowlist checks which *keys* appear, and
    ``model_hash`` is an allowed key; only the value would have changed. So the guard
    has to sit on the exporter and on the shape of the value.
    """

    HASH_SHAPE = re.compile(r"[0-9a-f]{12}")

    @staticmethod
    def _load_exporter() -> ModuleType:
        """Import ``tools/export_runs.py`` by path — ``tools`` is not a package."""
        spec = importlib.util.spec_from_file_location("export_runs", REPO_ROOT / "tools" / "export_runs.py")
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    @staticmethod
    def _write_run(model_dir: Path, summary: dict[str, Any]) -> None:
        results_dir = model_dir / "run_1" / "results"
        results_dir.mkdir(parents=True)
        (model_dir / "summary.json").write_text(json.dumps(summary), encoding="utf-8")
        (results_dir / "experiment_results.json").write_text(
            json.dumps(
                {
                    "results": {"fold_1": {"valid_losses": [1.0], "num_valid_samples": 1}},
                    "summary": {"pixel_error": {"mean": 1.0}},
                }
            ),
            encoding="utf-8",
        )

    def test_a_run_without_a_hash_is_refused(self, tmp_path: Path) -> None:
        """No hash means the run is unusable — not an invitation to name the folder."""
        exporter = self._load_exporter()
        model_dir = tmp_path / "vitpose_s_RODRIGO-DESKTOP"
        self._write_run(model_dir, {"config": {"model_name": "vitpose-s"}})

        assert exporter.export_run(model_dir) is None

    def test_a_run_with_a_hash_still_exports_that_hash(self, tmp_path: Path) -> None:
        """The refusal must not be achieved by breaking the normal path."""
        exporter = self._load_exporter()
        model_dir = tmp_path / "vitpose_s_RODRIGO-DESKTOP"
        self._write_run(model_dir, {"model_hash": "0123456789ab", "config": {}})

        record = exporter.export_run(model_dir)
        assert record is not None
        assert record["model_hash"] == "0123456789ab"

    def test_every_published_hash_has_the_hash_shape(self) -> None:
        """A directory name could not pass this even if one were ever emitted."""
        offenders = []
        with (REPO_ROOT / "results" / "runs.jsonl").open(encoding="utf-8") as handle:
            for lineno, line in enumerate(handle, start=1):
                if not line.strip():
                    continue
                value = json.loads(line).get("model_hash", "")
                if not self.HASH_SHAPE.fullmatch(value):
                    offenders.append((lineno, value))
        assert offenders == [], f"model_hash values that are not content hashes: {offenders}"


class TestRepositoryHygiene:
    def test_no_file_exceeds_the_size_budget(self) -> None:
        offenders = [
            (p.relative_to(REPO_ROOT), p.stat().st_size)
            for p in iter_tracked_files()
            if p.stat().st_size > MAX_FILE_BYTES
        ]
        assert offenders == [], f"files over 5 MB: {offenders}"

    def test_gitignore_blocks_the_dataset_directories(self) -> None:
        ignore = (REPO_ROOT / ".gitignore").read_text(encoding="utf-8")
        for required in ("data/", "Dados/", "*.avi", "*.jpg", "*.dcm", "*.pth", "*.ipynb"):
            assert required in ignore, f".gitignore must block {required}"

    def test_no_model_weights_are_committed(self) -> None:
        offenders = [
            p.relative_to(REPO_ROOT)
            for p in iter_tracked_files()
            if p.suffix in {".pt", ".pth", ".ckpt", ".safetensors", ".onnx"}
        ]
        assert offenders == [], f"weight files committed: {offenders}"
